<?php
/*
function holos_taxonomy_page_callback($term) {
  // Calling drupal_goto() here will result in an infinite loop.
  // This is the page callback for pages with a URL like taxonomy/term/1 so
  // there's no need to redirect...you're already where you need to be.
  // This function is used to build up the new page content for the taxonomy page

  // As a test just output the name of the term related to this page.
  return $term->name;
}


function holos_menu_alter (&$items) {
echo "TA";die();
  $items['categories/%taxonomy_term']['page callback'] = 'material_taxonomy_page_callback'; 

  // You don't need to return anything from this function as $items is passed in by reference...anything you change in that variable will be reflected in the $items var in the calling function.
}
*/
